export default {
  SET_MEAL_ON_ANALYSER: 'meals/SET_MEAL_ON_ANALYSER',
  ADD_OR_REMOVE_FOOD: 'meals/ADD_OR_REMOVE_FOOD',
  ADD_MEAL: 'meals/ADD_MEAL',
  SET_ALL_MEALS_IN_STATE: 'meals/SET_ALL_MEALS_IN_STATE',
  RESET_MEALS: 'meals/RESET_MEALS',
  SET_CONCEPT_PORTION_SIZE: 'meals/SET_CONCEPT_PORTION_SIZE',
  UPDATE_MACROS: 'meals/UPDATE_MACROS',
  SET_ACTIVE_MEAL_ID: 'meals/SET_ACTIVE_MEAL_ID',
  RESET_KEEP_LOGGED_IN: 'meals/RESET_KEEP_LOGGED_IN',
};
