/*
  UI
*/

export const OPEN_MODAL = "UI/OPEN_MODAL";
export const CLOSE_MODAL = "UI/CLOSE_MODAL";
export const SET_LOADING = "UI/SET_LOADING";
export const SET_PICTURE_ON_ANALYSER = "UI/SET_PICTURE_ON_ANALYSER";
export const CHANGE_DISPLAYING_MEAL = "UI/CHANGE_DISPLAYING_MEAL";
export const TOGGLE_DASHBOARD_LOADING = "UI/TOGGLE_DASHBOARD_LOADING";
export const TOGGLE_SIGN_UP_MODAL = "UI/TOGGLE_SIGN_UP_MODAL";
export const TOGGLE_LOGGED_IN = "UI/TOGGLE_LOGGED_IN";
export const TOGGLE_SIGN_UP_FORM_COMPLETED = "UI/TOGGLE_SIGN_UP_FORM_COMPLETED";
export const TOGGLE_WELCOME_MESSAGE = "UI/TOGGLE_WELCOME_MESSAGE";
export const TOGGLE_ADD_FOOD_MODAL = "UI/TOGGLE_ADD_FOOD_MODAL";
export const SET_STATUS_BAR_HEIGHT = "UI/SET_STATUS_BAR_HEIGHT";
export const SET_ACTIVE_CONCEPT_ID = "UI/SET_ACTIVE_CONCEPT_ID";
export const SET_ANALYSER_PROCESS_TRACKER = "UI/SET_ANALYSER_PROCESS_TRACKER";

/*
  FOODS
*/

export const SET_IN_STAGE_ONE = "FOODS/SET_IN_STAGE_ONE";
export const SET_IN_STAGE_TWO = "FOODS/SET_IN_STAGE_TWO";
export const SET_IN_STAGE_THREE = "FOODS/SET_IN_STAGE_THREE";
export const CHANGE_PORTION_SIZE = "FOODS/CHANGE_PORTION_SIZE";
export const RESET_FOODS = "FOODS/RESET_FOODS";
export const CHANGE_SELECTED_OPTION = "FOODS/CHANGE_SELECTED_OPTION";
export const CHANGE_OPTIONS = "FOODS/CHANGE_OPTIONS";

/*
  MEALS
*/

export const SET_MEAL_ON_ANALYSER = "MEALS/SET_MEAL_ON_ANALYSER";
export const ADD_OR_REMOVE_FOOD = "MEALS/ADD_OR_REMOVE_FOOD";
export const ADD_MEAL = "MEALS/ADD_MEAL";
export const SET_ALL_MEALS_IN_STATE = "MEALS/SET_ALL_MEALS_IN_STATE";
export const RESET_MEALS = "MEALS/RESET_MEALS";
export const UPDATE_MACROS = "MEALS/UPDATE_MACROS";

/*
  USER
*/

export const SET_USER = "USER/SET_USER";
export const RESET_USER = "USER/RESET_USER";
export const SET_USER_TOKEN = "USER/SET_USER_TOKEN";
