export default {
  SET_IN_STAGE_ONE: 'SET_IN_STAGE_ONE',
  SET_IN_STAGE_TWO: 'SET_IN_STAGE_TWO',
  SET_IN_STAGE_THREE: 'SET_IN_STAGE_THREE',
  CHANGE_PORTION_SIZE: 'CHANGE_PORTION_SIZE',
  RESET_FOODS: 'RESET_FOODS',
  CHANGE_SELECTED_OPTION: 'CHANGE_SELECTED_OPTION',
  CHANGE_OPTIONS: 'CHANGE_OPTIONS',
};
